from xmlWriter import *
EDITOR = "allacrity"


file = "rc.xml"
with open(file,"w") as f:
	versionTag(f,"1.0","UTF-8")

	openbox = longTag(f,0,"openbox")

	resistance = longTag(f,1,"resistance")
	tag(f,2,"g","strength",10)
	tag(f,2,"g","screen_edge_strength",20)
	resistance.close()

	focus = longTag(f,1,"focus")
	tag(f,2,"g","focusNew","yes")
	tag(f,2,"g","followMouse","no")
	tag(f,2,"g","focusLast","yes")
	tag(f,2,"g","focusDelay",200)
	tag(f,2,"g","raiseOnFocus","no")
	focus.close()

	placement = longTag(f,1,"placement")
	tag(f,2,"g","policy","Smart")
	tag(f,2,"g","center","yes")
	tag(f,2,"g","monitor","Primary")
	tag(f,2,"g","primaryMonitor",1)
	placement.close()

	theme = longTag(f,1,"theme")
	tag(f,2,"g","name","modern-grey")
	tag(f,2,"g","titleLayout","LIMC")
	tag(f,2,"g","keepBorder","no")
	tag(f,2,"g","animateIconify","yes")
	tag(f,2,"b","font",["place","ActiveWindow"],[["g","name","Hack"],["g","size","7"],["g","weight","Normal"],["g","slant","Normal"]])
	tag(f,2,"b","font",["place","InactiveWindow"],[["g","name","Hack"],["g","size","7"],["g","weight","Normal"],["g","slant","Normal"]])
	tag(f,2,"b","font",["place","MenuHeader"],[["g","name","Hack"],["g","size","7"],["g","weight","Normal"],["g","slant","Normal"]])
	tag(f,2,"b","font",["place","MenuHeader"],[["g","name","Hack"],["g","size","7"],["g","weight","Normal"],["g","slant","Normal"]])
	tag(f,2,"b","font",["place","ActiveOnScreenDisplay"],[["g","name","Hack"],["g","size","7"],["g","weight","Normal"],["g","slant","Normal"]])
	tag(f,2,"b","font",["place","InactiveOnScreenDisplay"],[["g","name","Hack"],["g","size","7"],["g","weight","Normal"],["g","slant","Normal"]])
	theme.close()

	desktop = longTag(f,1,"desktop")
	tag(f,2,"g","number",9)
	tag(f,2,"g","firstdesk",1)
	tag(f,2,"b","names",[],[["g","name","1"],["g","name","2"],["g","name","3"],["g","name","4"],["g","name","5"],["g","name","6"]])
	tag(f,2,"g","popupTime",875)
	desktop.close()

	resize = longTag(f,1,"resize")
	tag(f,2,"g","DrawContents","yes")
	tag(f,2,"g","popupShow","NonPixel")
	tag(f,2,"g","popupPosition","Center")
	tag(f,2,"b","popupFixedPosisiton",[],[["g","x","10"],["g","y","10"]])
	resize.close()

	# Margin Long Tag
	#tag(f,1,"margins",{},[["top",0],["bottom",0],["left",0],["right",0]])
	tag(f,1,"b","margins",[],[["g","top","0"],["g","bottom","0"],["g","left","0"],["g","right","0"]])

	dock = longTag(f,1,"dock")
	tag(f,2,"g","position","TopLeft")
	tag(f,2,"g","floatingX",0)
	tag(f,2,"g","floatingY",0)
	tag(f,2,"g","noStrut","no")
	tag(f,2,"g","stacking","Above")
	tag(f,2,"g","direction","Vertical")
	tag(f,2,"g","autoHide","no")
	tag(f,2,"g","hideDelay",300)
	tag(f,2,"g","showDelay",300)
	tag(f,2,"g","moveButtom","Midle")
	dock.close()

	keyboard = longTag(f,1,"keyboard")
	tag(f,2,"g","chainQuitKey","C-g")
	tag(f,2,"b","keybind",["key","C-S-Backspace"],[["b","action",["name","execute"],[["g","command","openbox -- reconfigure"]] ]] )
	#TODO - Add keybinds for all options to work with vim keybinds
	tag(f,2,"b","keybind",["key","A-C-Delete"],[["b","action",["name","execute"],[["g","command","oblogout"]] ]] )
	tag(f,2,"b","keybind",["key","C-A-Right"],[["b","action",["name","GoToDesktop"],[["g","to","right"],["g","wrap","no"]] ]] )
	tag(f,2,"b","keybind",["key","C-A-Left"],[["b","action",["name","GoToDesktop"],[["g","to","left"],["g","wrap","no"]] ]] )
	tag(f,2,"b","keybind",["key","W-S-Right"],[["b","action",["name","SendToDesktop"],[["g","to","right"],["g","wrap","no"]] ]] )
	tag(f,2,"b","keybind",["key","W-S-Left"],[["b","action",["name","SendToDesktop"],[["g","to","left"],["g","wrap","no"]] ]] )
	for i in range(1,7):
		gotoStr = "W-"+str(i)
		sendtoStr = "W-S-"+str(i)
		tag(f,2,"b","keybind",["key",gotoStr],[["b","action",["name","GoToDesktop"],[["g","to",str(i)],["g","wrap","no"]] ]] )
		tag(f,2,"b","keybind",["key",sendtoStr],[["b","action",["name","SendToDesktop"],[["g","to",str(i)],["g","wrap","no"]] ]] )
	tag(f,2,"b","keybind",["key","W-l"],[["s","action",["name","UnmaximiseFull"]],["b","action",["name","MoveResizeTo"],[["g","x","-0"],["g","y","0"],["g","width","50%"],["g","height","100%"]]]])

	tag(f,2,"b","keybind",["key","W-h"],[["s","action",["name","UnmaximiseFull"]],["b","action",["name","MoveResizeTo"],[["g","x","0"],["g","y","0"],["g","width","50%"],["g","height","100%"]]]])
	tag(f,2,"b","keybind",["key","W-j"],[["s","action",["name","UnmaximiseFull"]],["b","action",["name","MoveResizeTo"],[["g","x","0"],["g","y","0"],["g","width","100%"],["g","height","50%"]]]])
	tag(f,2,"b","keybind",["key","W-k"],[["s","action",["name","UnmaximiseFull"]],["b","action",["name","MoveResizeTo"],[["g","x","0"],["g","y","-0"],["g","width","100%"],["g","height","50%"]]]])

	# Fake Tiling
	tag(f,2,"b","keybind",["key","W-C-h"],[["s","action",["name","UnmaximiseFull"]],["b","action",["name","MoveResizeTo"],[["g","x","0"],["g","y","0"],["g","width","50%"],["g","height","50%"]]]])
	tag(f,2,"b","keybind",["key","W-A-h"],[["s","action",["name","UnmaximiseFull"]],["b","action",["name","MoveResizeTo"],[["g","x","0"],["g","y","-0"],["g","width","50%"],["g","height","50%"]]]])
	tag(f,2,"b","keybind",["key","W-C-l"],[["s","action",["name","UnmaximiseFull"]],["b","action",["name","MoveResizeTo"],[["g","x","-0"],["g","y","0"],["g","width","50%"],["g","height","50%"]]]])
	tag(f,2,"b","keybind",["key","W-A-l"],[["s","action",["name","UnmaximiseFull"]],["b","action",["name","MoveResizeTo"],[["g","x","-0"],["g","y","-0"],["g","width","50%"],["g","height","50%"]]]])

	tag(f,2,"b","keybind",["key","W-n"],[["s","action",["name","MaximizeFull"]]])
	tag(f,2,"b","keybind",["key","W-m"],[["s","action",["name","UnmaximizeFull"]],["b","action",["name","MoveResizeTo"],[["g","width","40%"],["g","height","40%"]],["g","action",["name","MoveToCenter"]]]])
	tag(f,2,"b","keybind",["key","S-A-h"],[["s","action",["name","SendToDesktopLeft"]]])
	tag(f,2,"b","keybind",["key","S-A-l"],[["s","action",["name","SendToDesktopRight"]]])
	tag(f,2,"b","keybind",["key","W-S-Right"],[["s","action",["name","DirectionCycleWindows"]]])
	tag(f,2,"b","keybind",["key","W-S-Left"],[["s","action",["name","DirectionCycleWindows"]]])
	tag(f,2,"b","keybind",["key","W-S-Up"],[["s","action",["name","DirectionCycleWindows"]]])
	tag(f,2,"b","keybind",["key","W-S-Down"],[["s","action",["name","DirectionCycleWindows"]]])
	tag(f,2,"b","keybind",["key","A-Escape"],[["s","action",["name","Lower"]],["s","action",["name","FocusToBottom"]],["s","action",["name","Unfocus"]]])
	tag(f,2,"b","keybind",["key","A-space"],[["b","action",["name","ShowMenu"],[["g","menu","client-menu"]] ]] )
	tag(f,2,"b","keybind",["key","XF86MonBrightnessUp"],[["b","action",["name","execute"],[["g","command","xbacklight +10"]] ]] )
	tag(f,2,"b","keybind",["key","XF86MonBrightnessDown"],[["b","action",["name","execute"],[["g","command","xbacklight -10"]] ]] )
	tag(f,2,"b","keybind",["key","A-F2"],[["b","action",["name","execute"],[["g","command","gmrun"],["b","smartnotify",[],[["g","enabled","yes"],["g","name","Run Program"]]] ]]] )
	tag(f,2,"b","keybind",["key","W-S-d"],[["b","action",["name","execute"],[["g","command","dmenu_run -i -nb '#191919' -nf '#fea63c' -sf '#191919' -fn 'NotoMonoRegular:bold:pixelsize=14'"]] ]])
	tag(f,2,"b","keybind",["key","A-F4"],[["s","action",["name","Close"]]])
	tag(f,2,"b","keybind",["key","A-F5"],[["s","action",["name","Iconify"]]])
	tag(f,2,"b","keybind",["key","A-F6"],[["s","action",["name","ToggleDecorations"]]])
	tag(f,2,"b","keybind",["key","A-F8"],[["s","action",["name","ToggleShowDesktop"]]])
	tag(f,2,"b","keybind",["key","W-d"],[["s","action",["name","ToggleShowDesktop"]]])
	tag(f,2,"b","keybind",["key","C-A-e"],[["b","action",["name","execute"],[["g","command","thunar"]] ]] )
	tag(f,2,"b","keybind",["key","W-e"],[["b","action",["name","execute"],[["g","command",EDITOR+" -e ranger"]] ]] )	
	tag(f,2,"b","keybind",["key","C-A-t"],[["b","action",["name","execute"],[["g","command",EDITOR+" -e htop"]] ]] )
	tag(f,2,"b","keybind",["key","W-t"],[["b","action",["name","execute"],[["g","command",EDITOR]] ]] )
	tag(f,2,"b","keybind",["key","C-A-b"],[["b","action",["name","execute"],[["g","command","qutebrowser"]] ]] )
	tag(f,2,"b","keybind",["key","W-b"],[["b","action",["name","execute"],[["g","command","firefox"]] ]] )
	tag(f,2,"b","keybind",["key","W-a"],[["b","action",["name","execute"],[["g","command",EDITOR+" -e vim"]] ]] )
	tag(f,2,"b","keybind",["key","C-A-a"],[["b","action",["name","execute"],[["g","command","atom"]] ]] )
	tag(f,2,"b","keybind",["key","W-r"],[["b","action",["name","execute"],[["g","command","rofi-theme-selector"]] ]] )
	tag(f,2,"b","keybind",["key","W-Escape"],[["b","action",["name","execute"],[["g","command","xkill"]] ]] )
	tag(f,2,"b","keybind",["key","W-Tab"],[["b","action",["name","execute"],[["g","command","client-list-combined-menu"]] ]] )
	tag(f,2,"b","keybind",["key","C-Shift-space"],[["b","action",["name","execute"],[["g","command","rofi -modi drun,run -show drun -fullscreen -font \"Roboto Regular 8\""]] ]] )
	tag(f,2,"b","keybind",["key","C-space"],[["b","action",["name","execute"],[["g","command","rofi -modi drun,run -show \"drun\" -font \"Roboto Regular 8\""]] ]] )
	tag(f,2,"b","keybind",["key","C-A-Space"],[["b","action",["name","execute"],[["g","command","rofi -show run"]] ]] )
	tag(f,2,"b","keybind",["key","W-F11"],[["b","action",["name","execute"],[["g","command","rofi -modi drun,run -show drun -fullscreen -font \"Roboto Regular 8\""]] ]] )
	tag(f,2,"b","keybind",["key","W-F12"],[["b","action",["name","execute"],[["g","command","rofi -modi drun,run -show \"drun\" -font \"Roboto Regular 8\""]] ]] )
	tag(f,2,"b","keybind",["key","W-space"],[["b","action",["name","ShowMenu"],[["g","command","root-menu"]] ]] )
	tag(f,2,"b","keybind",["key","W-A-Left"],[["s","action",["name","UnmaximiseFull"]],["b","action",["name","MoveResizeTo"],[["g","x","0"],["g","y","0"],["g","width","50%"],["g","height","100%"]]]])
	tag(f,2,"b","keybind",["key","W-A-Right"],[["s","action",["name","UnmaximiseFull"]],["b","action",["name","MoveResizeTo"],[["g","x","-0"],["g","y","0"],["g","width","50%"],["g","height","100%"]]]])
	tag(f,2,"b","keybind",["key","A-r"],[["s","action",["name","Close"]]])
	tag(f,2,"b","keybind",["key","A-m"],[["s","action",["name","Move"]]])
	tag(f,2,"b","keybind",["key","W-q"],[["s","action",["name","Close"]]])
	tag(f,2,"b","keybind",["key","W-F1"],[["b","action",["name","execute"],[["g","command","exo-open --launch webbrowser"]] ]] )
	tag(f,2,"b","keybind",["key","W-F4"],[["b","action",["name","execute"],[["g","command","gimp"]] ]] )
	tag(f,2,"b","keybind",["key","W-F6"],[["b","action",["name","execute"],[["g","command","vlc"]] ]] )
	tag(f,2,"b","keybind",["key","W-F7"],[["b","action",["name","execute"],[["g","command","virtualbox"]] ]] )
	tag(f,2,"b","keybind",["key","W-F8"],[["b","action",["name","execute"],[["g","command","thunar"]] ]] )
	tag(f,2,"b","keybind",["key","W-F10"],[["b","action",["name","execute"],[["g","command","spotify"]] ]] )
	#tag(f,2,"b","keybind",["key","C-S-Escape"],[["b","action",["name","execute"],[["g","command","xfce4-taskmanager"]] ]] )
	tag(f,2,"b","keybind",["key","W-p"],[["b","action",["name","execute"],[["g","command","obmenu3"]] ]] )
	tag(f,2,"b","keybind",["key","W-u"],[["b","action",["name","execute"],[["g","command","obkey"]] ]] )
	tag(f,2,"b","keybind",["key","W-s"],[["b","action",["name","execute"],[["g","command","spotify"]] ]] )
	tag(f,2,"b","keybind",["key","W-i"],[["b","action",["name","execute"],[["g","command","pavucontrol"]] ]] )
	tag(f,2,"b","keybind",["key","W-v"],[["b","action",["name","execute"],[["g","command","nitrogen"]] ]] )
	tag(f,2,"b","keybind",["key","W-o"],[["b","action",["name","execute"],[["g","command","obconf"]] ]] )
	tag(f,2,"b","keybind",["key","W-S-x"],[["b","action",["name","execute"],[["g","command","betterlockscreen -l"]] ]] )
	tag(f,2,"b","keybind",["key","XF86AudioRaiseVolume"],[["b","action",["name","execute"],[["g","command","sh -c \"pactl set-sink-mute - false ; pactl set-sink-volume 0 +5%\""]] ]] )
	tag(f,2,"b","keybind",["key","XF86AudioLowerVolume"],[["b","action",["name","execute"],[["g","command","sh -c \"pactl set-sink-mute - false ; pactl set-sink-volume 0 -5%\""]] ]] )
	tag(f,2,"b","keybind",["key","XF86AudioMute"],[["b","action",["name","execute"],[["g","command","sh -c \"pactl set-sink-mute - toggle ; pactl set-sink-volume 0 20%\""]] ]] )
	keyboard.close()

	mouse = longTag(f,1,"mouse")
	tag(f,2,"g","dragThreshold","8")
	tag(f,2,"g","screenEdgeWarpTime","400")
	tag(f,2,"g","screenEdgeWarpMouse","false")

	frame = longTag(f,1,"context",["name","Frame"])
	tag(f,2,"b","mousebind",[["action","Press"],["button","A-Left"]],[["s","action",["name","Focus"]],["s","action",["name","Raise"]]])
	tag(f,2,"b","mousebind",[["action","Click"],["button","A-Left"]],[["s","action",["name","Unshade"]]])
	tag(f,2,"b","mousebind",[["action","Drag"],["button","A-Left"]],[["s","action",["name","Move"]]])
	
	tag(f,2,"b","mousebind",[["action","Press"],["button","A-Right"]],[["s","action",["name","Focus"]],["s","action",["name","Raise"]],["s","action",["name","Unshade"]]])
	tag(f,2,"b","mousebind",[["action","Drag"],["button","A-Right"]],[["s","action",["name","Resize"]]])

	frame.close()
	mouse.close()

	menu = longTag(f,1,"menu")
	tag(f,2,"g","file","menu.xml")
	tag(f,2,"g","hideDelay","200")
	tag(f,2,"g","middle","yes")
	tag(f,2,"g","submenuShowDelay","100")
	tag(f,2,"g","applicationIcons","yes")
	tag(f,2,"g","manageDesktops","yes")
	menu.close()

	app = longTag(f,1,"applications")	
	app.close()

	openbox.close()
